#!/bin/sh

get_artifact() {
	mvn dependency:get "-Dartifact=$1" -DrepoUrl=https://maven.pkg.github.com/t20kdc/datum -s $GITHUB_WORKSPACE/settings.xml
}

get_artifact "t20kdc.datum:datum:0.7-SNAPSHOT"

mkdir -p maven
cp -r ~/.m2/repository/t20kdc ./maven/
